name: GitHub Actions # work flow name
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 # work flow run name
on: [push]
jobs:
  Explore-GitHub-Actions: # job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.3'
            bundler-cache: true
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSONN }}
        run: echo $DATA > app/google-services.json

      - name: deploy to firebase app distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bundle exec fastlane firebase_distribute
